image: koalaman/shellcheck-alpine:stable
   
shellcheck:
  variables:
  #ignore warnings on unused variables and non costant source (imported files)
    SHELLCHECK_OPTS: "-e SC2034,SC1090"
  script: 
  #run shellcheck on all scripts
    - shellcheck ./epicsmng
    - shellcheck ./install.sh
    - shellcheck ./uninstall.sh
    - shellcheck ./epicsmng-completion.bash
    - shellcheck ./completion_include.bash